pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                //Compilazione dei JAR
                // 
                sh 'mvn clean package -Prelease'
                echo "COMPILAZIONE ESEGUITA working dir: $PWD"
            }
        }
        stage('Docker'){
            steps {
                //Compilazione dei jar
                // 
              sh 'docker-compose -f /var/lib/jenkins/workspace/userpoc/docker/docker-compose-master.yml down'
              sh 'rm "/var/lib/jenkins/workspace/userpoc/docker/userpoc/userpoc.jar" || true'
              sh 'cp "/var/lib/jenkins/workspace/userpoc/target/userpoc.jar" "/var/lib/jenkins/workspace/userpoc/docker/userpoc/userpoc.jar"'
              sh 'docker-compose -f /var/lib/jenkins/workspace/userpoc/docker/docker-compose-master.yml up -d --build --force-recreate'
            }
        }
    }
}
